### ISSUE TITLE
Lambda powertool not weaving properly

### ISSUE THREAD

**Issue by mihai1git** [aws-powertools/powertools-lambda-java#1026]
I opened a question in re:Post with this issue: https://repost.aws/questions/QUfzMemL62RwuNEvRjIlKxSg/lambda-powertool-not-working-properly

## Expected Behavior

Log the event of the function automatically, in JSON format
```   
@Logging(logEvent = true,clearState = true)
@Override
public String handleRequest(S3Event event, Context context) {
```

## Current Behavior

If I build the archive using AWS Toolkit and Java8, the weaving is not done at all (no classes are generated).

After the partial solution from re:Post (build with Java11) the weaving is done, but the log does not work (in decompiled classes I do not see the log invocation). 
In this case one more problem appear: If I use the standard deploy of AWS Toolkit, the target Lambda function from AWS is not visible because it runs on Java11. According to AWS Support, this is an issue of AWS Toolkit: it makes deploys only on AWS Lambda Runtimes with Java8. So with Java11, I have to do the deploy using Eclipse Maven procedures and upload the archive manually in AWS Lambda.

## Possible Solution

waiting ....

## Steps to Reproduce (for bugs)

1. Use class and pom.xml attached
[pom.xml.txt](https://github.com/awslabs/aws-lambda-powertools-java/files/10308362/pom.xml.txt)
[LambdaFunctionHandler.java.txt](https://github.com/awslabs/aws-lambda-powertools-java/files/10308363/LambdaFunctionHandler.java.txt)

2. See decompiled generated weaved classes attached
[LambdaFunctionHandler1.class.txt](https://github.com/awslabs/aws-lambda-powertools-java/files/10308359/LambdaFunctionHandler1.class.txt)
[LambdaFunctionHandler2.class.txt](https://github.com/awslabs/aws-lambda-powertools-java/files/10308360/LambdaFunctionHandler2.class.txt)

## Environment
- Eclipse has Version: 2018-12 (4.10.0) Build id: 20181214-0600 that ran on Java 8
- <maven.compiler.source>11</maven.compiler.source>

* **Powertools version used**:
1.12.3
* **Packaging format (Layers, Maven/Gradle)**:
Maven
* **AWS Lambda function runtime:**
Java8, Java11
* **Debugging logs**
Eclipse Maven build logs:  [EclipseMavenbuildLog.txt](https://github.com/awslabs/aws-lambda-powertools-java/files/10308438/EclipseMavenbuildLog.txt)

**Comment by jeromevdl** [comment]
Hi @mihai1git,

Thanks for reporting this.

To ensure this is an issue on Lambda Powertools, could you please try to build the package with maven only: `mvn clean package` ? Make sure the JDK used in your shell is the one corresponding to the maven.compiler.source / maven.compiler.target and to your lambda function configuration.

In your shell: please type `java --version`, `mvn --version` and let us know.

**Comment by mihai1git** [comment]
Hi @jeromevdl 

Regarding your request: build the package with maven only, I have to say that I already built the package without AWS Toolkit. The package was built with Eclipse Maven. When you said Maven only, did you have in mind this kind of build, or some windows command line run ? 

When running `java --version`, `mvn --version` in windows command line I had the output: 
```
java --version
java 11.0.2 2019-01-15 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.2+9-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.2+9-LTS, mixed mode)
```

```
mvn --version
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Java version: 11.0.2, vendor: Oracle Corporation, runtime: D:\java\jdk-11.0.2
Default locale: en_GB, platform encoding: Cp1250
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"
```

When built with Eclipse Maven I already used options: Project -> Run As -> Maven clean, and then,  Project -> Run As -> Maven build, so I believe that it was used only Maven and according to specifications in pom.xml file. The versions of the Java and Maven in this case are included in the debugging log that I already attached in previous post (Eclipse Maven build logs: [EclipseMavenbuildLog.txt](https://github.com/awslabs/aws-lambda-powertools-java/files/10308438/EclipseMavenbuildLog.txt)) :
```
Apache Maven 3.5.3 (3383c37e1f9e9b3bc3df5050c29c8aff9f295297; 2018-02-24T21:49:05+02:00)
Maven home: D:\workspace_2019\AWS_lambda_RekonUsers\EMBEDDED
Java version: 11.0.2, vendor: Oracle Corporation
Java home: D:\java\jdk-11.0.2
Default locale: en_GB, platform encoding: UTF-8
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"
```
When I look for environment variable JAVA_HOME, I have in the windows command line:
```
set JAVA_HOME
JAVA_HOME=D:\java\jdk-11.0.2
```
So, from the maven build log, the used java was 11, the same from maven.compiler.source / maven.compiler.target. If you need more details about the issue, please let me know.

Have a good day,
Mihai

**Comment by msailes** [comment]
Could this be a problem with the AWS Toolkit for Eclipse, which is end of life on May 31st 2023?

Have you tried building and deploying the code in another way?

**Comment by mihai1git** [comment]
> Could this be a problem with the AWS Toolkit for Eclipse, which is end of life on May 31st 2023?
> 
> Have you tried building and deploying the code in another way?
Hi,
As described in "Current Behaviour", when I've built the package with Eclipse Maven (build with Java11) the weaving is done, but the log does not work (in decompiled classes I do not see the log invocation). Maybe there is a mistake in my config files. If this works on your side, could you please send a valid configuration.
Thank you a lot,

**Comment by jeromevdl** [comment]
Hi @mihai1git ,

I used your pom and your java class (just removed the dao part) and it actually logs properly...

What I did however is using SAM to build and deploy the project: `sam init` (you can now even select `7 - Hello World Example With Powertools`), I replaced the pom with yours, add your code and `sam build` and `sam deploy -g`. 

I also tried to do a `mvn clean package` and deploy the fat jar (be careful to use this one, not the other jar which does not contain the dependencies), and it also logs.

```shell
$ java --version
openjdk 11.0.18 2023-01-17 LTS
OpenJDK Runtime Environment Corretto-11.0.18.10.1 (build 11.0.18+10-LTS)
OpenJDK 64-Bit Server VM Corretto-11.0.18.10.1 (build 11.0.18+10-LTS, mixed mode)
```

```shell
$ mvn --version
Apache Maven 3.8.7 (b89d5959fcde851dcb1c8946a785a163f14e1e29)
Maven home: /opt/homebrew/Cellar/maven/3.8.7/libexec
Java version: 11.0.18, vendor: Amazon.com Inc., runtime: /Library/Java/JavaVirtualMachines/amazon-corretto-11.jdk/Contents/Home
Default locale: en_CH, platform encoding: UTF-8
OS name: "mac os x", version: "12.6.3", arch: "x86_64", family: "mac"
```

I'm not sure what Eclipse is doing or what the AWS Toolkit is doing. I would recommend using SAM (or another Infra as code framework to handle the build and deploy of your function/app). Also you can upgrade to version 1.14 of Powertools.

**Comment by jeromevdl** [comment]
Any update @mihai1git , were you able to fix your problem using SAM or any other way?

**Comment by mihai1git** [comment]
Hello,

Because I'm using Powertools from home, for no production purposes, my priorities changed and I did not fixed it. I haven't tried SAM, because I'm not used with it at this moment, but I plan to use it in the future.
Because of these, and because in your environment works, I will close this issue at this moment, and I will open it in the future if necessary, after I will try SAM.

Thank you,
Mihai ADAM
