### ISSUE TITLE
Docs: Improve Examples coverage

### ISSUE THREAD

**Issue by scottgerring** [aws-powertools/powertools-lambda-java#1067]
### What were you searching in the docs?

The examples that will be packaged as part of #1051

### How can we improve?

At a coarse level, we are missing example coverage of `powertools-cloudformation` and the coverage of the tracing, logging, and metrics library doesn't line up with the module structure.

At a fine-grained level we should check feature coverage within each example and expand as necessary. 

### Acknowledgment

- [X] I understand the final update might be different from my proposed suggestion, or refused.

**Comment by jeromevdl** [comment]
Adding that we should have examples using other frameworks than SAM (from the discussion here: https://github.com/awslabs/aws-lambda-powertools-java/issues/1074): SST, serverless fwk...

**Comment by mriccia** [comment]
I started working on this in the `cf-customresource-examples` branch

**Comment by scottgerring** [comment]
We are missing also an example for `powertools-large-messages` !

**Comment by scottgerring** [comment]
Example for `powertools-large-messages` moved into ticket #1353 to be worked on separately. 
@AlexeySoshin working on this ticket on CDK and Serverless Framework.

**Comment by AlexeySoshin** [comment]
Sure, happy to take #1353 part!

**Comment by scottgerring** [comment]
I will add an example for Gradle in #1359

**Comment by jeromevdl** [comment]
@skal111 will take that one: #1445 (terraform)

**Comment by scottgerring** [comment]
At this point we have such extensive example coverage we can close this.
