### ISSUE TITLE
Maintenance: Enable auto-merge for non-failed Github PRs

### ISSUE THREAD

**Issue by machafer** [aws-powertools/powertools-lambda-java#1075]
### Summary

Over 10 PRs are automatically created per week to update dependencies. Project maintainers need to manually approve merging of the successful ones. 

### Why is this needed?

Improve governance and reduce manual work.

### Which area does this relate to?

Automation, Governance

### Solution
- Review and fix "Auto merge if dependabot PR" Github workflow [here](https://github.com/awslabs/aws-lambda-powertools-java/blob/master/.github/workflows/auto-merge.yml). Last execution is available [here](https://github.com/awslabs/aws-lambda-powertools-java/actions/runs/4252081145/jobs/7395224659).
- Review and define which dependencies can be trusted for auto-merging.

### Acknowledgment

- [X] This request meets [Lambda Powertools Tenets](https://awslabs.github.io/aws-lambda-powertools-java/#tenets)
- [ ] Should this be considered in other Lambda Powertools languages? i.e. [Python](https://github.com/awslabs/aws-lambda-powertools-python/), [TypeScript](https://github.com/awslabs/aws-lambda-powertools-typescript/)

**Comment by jeromevdl** [comment]
It woks now. A few have been merged.
