### ISSUE TITLE
Maintenance: v2 - rename 'core' module 

### ISSUE THREAD

**Issue by scottgerring** [aws-powertools/powertools-lambda-java#1076]
### Summary

The 'powertools-core' module provides common functionality to the other powertools modules, and does not have anything to do with the externally-facing idea of 'powertools core functionality' [logging/tracing/metrics]./ 

I propose that we rename this to something else (common? shared? 🤷 ) as part of V2.

### Why is this needed?

It's a confusing detail where our interface - the modules we expose - doesn't match the documentation in a strange fashion. You'd be forgiven for thinking if you ask for powertools-core you get all of logging/tracing/metrics.

### Which area does this relate to?

Other

### Acknowledgment

- [X] This request meets [Lambda Powertools Tenets](https://awslabs.github.io/aws-lambda-powertools-java/#tenets)
- [ ] Should this be considered in other Lambda Powertools languages? i.e. [Python](https://github.com/awslabs/aws-lambda-powertools-python/), [TypeScript](https://github.com/awslabs/aws-lambda-powertools-typescript/)

**Comment by YuvrajPraveenSingh** [comment]
O would like to work on this if possible

**Comment by jeromevdl** [comment]
@YuvrajPraveenSingh thanks for your support. However this is something we'll do on a v2 and therefore not right now.
