### ISSUE TITLE
Bug: Treat missing idempotency key as non-idempotent transaction

### ISSUE THREAD

**Issue by jeromevdl** [aws-powertools/powertools-lambda-java#1200]
Should not store data in persistence store when idempotency key is null.

## Expected Behavior
By default, treat a transaction that is missing idempotency key as a NO-OP transaction. That means, we will continue to log a warning and will not save at the configured persistence storage layer.

This prevents mistakes when an application is designed to optionally send a unique value (e.g., X-Idempotency-Value) and `NULL` doesn't get a unique sentinel value (e.g., UUID) in its absence.

## Current Behavior
[By default,](https://awslabs.github.io/aws-lambda-powertools-java/utilities/idempotency/#making-idempotency-key-required)`ThrowOnNoIdempotencyKey ` is set to `false`. This means we will log a warning when the idempotency key is missing, since we don't know if that's intentional or not. [However we continue treating the transaction like we normally would](https://github.com/awslabs/aws-lambda-powertools-java/blob/c96c0ad6be7776951f6afdfda3ad70c9b20992b2/powertools-idempotency/src/main/java/software/amazon/lambda/powertools/idempotency/persistence/BasePersistenceStore.java#L225), hash the null value, and save it in the persistence store.

[Test](https://github.com/awslabs/aws-lambda-powertools-java/blob/c96c0ad6be7776951f6afdfda3ad70c9b20992b2/powertools-idempotency/src/test/java/software/amazon/lambda/powertools/idempotency/persistence/BasePersistenceStoreTest.java#L146) that confirms this behaviour.

## Possible Solution

https://github.com/awslabs/aws-lambda-powertools-typescript/issues/1501

## Steps to Reproduce (for bugs)
1. Call the lambda handler twice with a null idempotency key

## Environment

* **Powertools for AWS Lambda (Java) version used**: <=1.15
* **Packaging format (Layers, Maven/Gradle)**: *
* **AWS Lambda function runtime:** *
* **Debugging logs**

**Comment by jeromevdl** [comment]
Fixed with #1201

**Comment by scottgerring** [comment]
Released in 1.16.0
