### ISSUE TITLE
Maintenance: remove GH Pages

### ISSUE THREAD

**Issue by sthulb** [aws-powertools/powertools-lambda-java#1212]
### Summary

We no longer use GH pages for hosting the docs, we should remove the code from GitHub Actions.

### Why is this needed?

We now host docs on docs.powertools.aws.dev instead of GitHub Pages

### Which area does this relate to?

Other

### Solution

Remove GH pages from GH actions

### Acknowledgment

- [X] This request meets [Powertools for AWS Lambda (Java) Tenets](https://docs.powertools.aws.dev/lambda-java/#tenets)
- [X] Should this be considered in other Powertools for AWS Lambda (Java) languages? i.e. [Python](https://github.com/aws-powertools/powertools-lambda-python/), [TypeScript](https://github.com/aws-powertools/powertools-lambda-typescript/)

**Comment by jeromevdl** [comment]
fixed with #1211
