### ISSUE TITLE
Maintenance: Decouple samples from the parent pom

### ISSUE THREAD

**Issue by jeromevdl** [aws-powertools/powertools-lambda-java#1224]
### Summary

Currently, samples (`powertools-examples`) are inheriting stuff from the parent pom (eg. aspectJ config and others) and are not really usable as is by developers. We should make them independent/freestanding so that anyone can take it without looking at our parent configuration.

### Why is this needed?

Current samples are not really reusable as is, developers would need to figure out what to take from our parent pom to put in their code.

### Which area does this relate to?

Other

### Solution

remove the following from https://github.com/aws-powertools/powertools-lambda-java/blob/main/examples/pom.xml: 

```xml
<parent>
    <artifactId>powertools-parent</artifactId>
    <groupId>software.amazon.lambda</groupId>
    <version>1.15.0</version>
</parent>
```

And make sure samples are still working, especially make sure to take the aspectj-maven-plugin configuration.

### Acknowledgment

- [X] This request meets [Powertools for AWS Lambda (Java) Tenets](https://docs.powertools.aws.dev/lambda-java/#tenets)
- [ ] Should this be considered in other Powertools for AWS Lambda (Java) languages? i.e. [Python](https://github.com/aws-powertools/powertools-lambda-python/), [TypeScript](https://github.com/aws-powertools/powertools-lambda-typescript/)

**Comment by scottgerring** [comment]
I think this makes sense. However we should make sure that the build still breaks if a change in the powertools modules breaks the examples. If we just remove the parent from the examples pom, I don't think this will be the case. Happy to be wrong on this one - just want to make sure that we don't end up in a situation where we can accidentally break the examples and not notice.

**Comment by jeromevdl** [comment]
We can certainly keep samples as modules so that we build them with the rest. But we remove the `<parent>` flag to avoid inheriting stuff. And we put them last in the list of modules and change `package` with `install` to keep this "dependency" and make sure samples fail if there's an issue in powertools.

**Comment by scottgerring** [comment]
> We can certainly keep samples as modules so that we build them with the rest. But we remove the `<parent>` flag to avoid inheriting stuff. And we put them last

Great! I didn't know you could have modules without the parent in the other direction. Exactly what we want. I think we should also do the same the next layer down - `parent -> samples parent -> [each example]` . That way you really can just grab a sample by itself and use it, rather than having to grab the whole `samples` tree.

> I also think we should adopt the x.y.z-SNAPSHOT notation while in development.

+1

As I introduced the change that bundled all this together into one build, I'm happy to put together a branch to make this change
