### ISSUE TITLE
Maintenance: Update docs base origin url

### ISSUE THREAD

**Issue by hjgraca** [aws-powertools/powertools-lambda-java#1237]
### Summary

Update base origin variable in mkdocs javascript

### Why is this needed?

Due to the move to the new domain `docs.powertools.aws.dev` we need to update the old entries that point to `awslabs.github.io`

### Which area does this relate to?

Governance

### Solution

Change `awslabs.github.io` to `docs.powertools.aws.dev`

### Acknowledgment

- [X] This request meets [Powertools for AWS Lambda (Java) Tenets](https://docs.powertools.aws.dev/lambda-java/#tenets)
- [X] Should this be considered in other Powertools for AWS Lambda (Java) languages? i.e. [Python](https://github.com/aws-powertools/powertools-lambda-python/), [TypeScript](https://github.com/aws-powertools/powertools-lambda-typescript/)

**Comment by jeromevdl** [comment]
fixed in #1238
