### ISSUE TITLE
Docs: Improve installation documentation

### ISSUE THREAD

**Issue by jeromevdl** [aws-powertools/powertools-lambda-java#1271]
### What were you searching in the docs?

Current documentation is referencing the new version of the aspectj plugin which does not work with JDK 1.8 unless we enforce version of aspectj-rt in the plugin configuration, but documentation does not specify this.

Also, we recently received [questions](https://github.com/aws-powertools/powertools-lambda-java/discussions/1246) and [issues](https://github.com/aws-powertools/powertools-lambda-java/issues/1128) which were solved by explaining how to configure the aspectJ plugin.

Finally, installation of the core modules is described only in the home page, not in the modules themselves.

### How can we improve?

- Describe the installation steps (especially related to aspectJ plugin) for both Java 1.8 and Java 11+.
- Describe the installation steps in all modules that leverage aspectJ, especially core modules that don't have it today.

### Acknowledgment

- [X] I understand the final update might be different from my proposed suggestion, or refused.

**Comment by mriccia** [comment]
should this be closed, now that the PR is merged?

**Comment by jeromevdl** [comment]
closing as fixed, thanks @mriccia
