### ISSUE TITLE
Maintenance: append user agent to AWS SDK clients

### ISSUE THREAD

**Issue by jeromevdl** [aws-powertools/powertools-lambda-java#1274]
### Summary

The AWS SDK v2 allows to add user agent headers to the requests made using its clients.

### Why is this needed?

So that AWS can attribute requests made to its API when using Powertools.

### Which area does this relate to?

Governance

### Solution

Expose a shared function (in core module) that takes a client and adds Powertools-related user agents to the request. This shared function can then be used by other Powertools utilities that make requests to AWS APIs. Check [SDK documentation](https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/core/client/config/SdkAdvancedClientOption.html) and [typescript implementation](https://github.com/aws-powertools/powertools-lambda-typescript/blob/main/packages/commons/src/userAgentMiddleware.ts) (and [usage](https://github.com/aws-powertools/powertools-lambda-typescript/blob/2eb7ab3cb84e9f57378ca8f3c8d27e7912c18a3d/packages/idempotency/src/persistence/DynamoDBPersistenceLayer.ts#L92)). 
 
Impacted modules:
- tracing (X-ray)
- parameters (SSM Parameters, Secrets Manager, DynamoDB, AppConfig)
- idempotency (DynamoDB)
- sqs (SQS)

### Acknowledgment

- [X] This request meets [Powertools for AWS Lambda (Java) Tenets](https://docs.powertools.aws.dev/lambda-java/#tenets)
- [ ] Should this be considered in other Powertools for AWS Lambda (Java) languages? i.e. [Python](https://github.com/aws-powertools/powertools-lambda-python/), [TypeScript](https://github.com/aws-powertools/powertools-lambda-typescript/)

**Comment by eldimi** [comment]
I will have a look into this

**Comment by scottgerring** [comment]
Thanks @eldimi - I'll assign it to you then so we can keep an overview of what's going on :D
