### ISSUE TITLE
Docs: Improve SAM templates

### ISSUE THREAD

**Issue by jeromevdl** [aws-powertools/powertools-lambda-java#1278]
### What were you searching in the docs?

It's not in the doc per se, but the SAM templates (https://github.com/aws/aws-sam-cli-app-templates/pulls) are outdated:
- old version of powertools
- configuration of the aspectJ plugin (see #1273)

### How can we improve?

- bump powertools version (1.16.0)
- update the v11+ configuration to use the `dev.aspectj` plugin instead of `org.codehaus.mojo`
- test that it's working (logs, traces, metric) when creating a project and running it

### Got a suggestion in mind?

- optional : add a gradle version which we don't have today (maybe create another PR for that)

### Acknowledgment

- [X] I understand the final update might be different from my proposed suggestion, or refused.

**Comment by scottgerring** [comment]
@alexeysoshin are you interested in picking this one up?

**Comment by AlexeySoshin** [comment]
Happy to pick this 😄

**Comment by AlexeySoshin** [comment]
@jeromevdl When you say "add a gradle version which we don't have today (maybe create another PR for that)" do you mean moving to Gradle 8? Or adding Gradle to Java 11 project? Or something else?

**Comment by AlexeySoshin** [comment]
@scottgerring @jeromevdl 

This has been merged now.

**Comment by scottgerring** [comment]
Do we want to add a link to the examples README here to point this example out?

**Comment by jeromevdl** [comment]
It's not something delivered in the next release. Closing.
