### ISSUE TITLE
[Support Powertools for AWS Lambda (Java)]: Europace AG

### ISSUE THREAD

**Issue by roamingthings** [aws-powertools/powertools-lambda-java#1286]
### Organization Name

Europace AG

### Your Name

Alexander Sparkowsky

### Your current position

Tech Lead

### (Optional) Use case

We are using various packages of the Powertools for AWS Lambda (Java) to speed up our development.
Most helpful are the parameters, idempotency and observability packages.

### Also using other Powertools for AWS Lambda (Java) languages?

- [ ] Python
- [ ] TypeScript
- [ ] .NET

**Comment by jeromevdl** [comment]
Thank you very much @roamingthings for your support. We'll update the README to mention this.

Let us know if you would need additional features or improvements. We're working on the v2 definition right now, so it's a good time to share your thoughts ;)

**Comment by msailes** [comment]
Thanks again, you can now see reference customers in the readme.
