### ISSUE TITLE
Docs: Add & improve community documentation

### ISSUE THREAD

**Issue by scottgerring** [aws-powertools/powertools-lambda-java#1295]
### What were you searching in the docs?

We should add a maintainers and a contributors guide. We can use the Python ones for reference. 

### How can we improve?

Add the missing section

### Acknowledgment

- [X] I understand the final update might be different from my proposed suggestion, or refused.

**Comment by scottgerring** [comment]
Maintainers guide is done. Contributors guide outstanding.

**Comment by jeromevdl** [comment]
Are we good now ? can we close this one ?

**Comment by scottgerring** [comment]
Yes!
