### ISSUE TITLE
HelloWorldStreamFunction in examples fails with sam

### ISSUE THREAD

**Issue by scottgerring** [aws-powertools/powertools-lambda-java#1369]
Running `sam local invoke` on any of the examples in `powertools-examples-core` and invoking the streaming variant results in an error:

```bash
> sam local invoke HelloWorldStreamFunction
.....
Error: Expecting value: line 1 column 1 (char 0)
Traceback:
  File "/usr/local/Cellar/aws-sam-cli/1.95.0/libexec/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
```
The issue seems to be that the streaming handler doesn't return a result at all. We should fix this, as it's a rabbit hole users may get stuck in, thinking their is something wrong with their code.

The issue seems to be this one: https://github.com/aws/aws-sam-cli/issues/4656

## Expected Behavior
Examples deploy and can be invoked locally with SAM without error.

## Current Behavior
`HelloWorldStreamFunction` example doesn't return a value, and SAM errors out for a local invoke.

## Possible Solution
Make the `HelloWorldStreamFunction` example code return a value.

## Environment

* **Powertools for AWS Lambda (Java) version used**: 1.16.1
* **Packaging format (Layers, Maven/Gradle)**: N/A
* **AWS Lambda function runtime:** HelloWorldStreamFunction

**Comment by jasoniharris** [comment]
@scottgerring Please assign to me. Had a chat with Michele.

**Comment by AlexeySoshin** [comment]
@scottgerring 
I'm wondering what are we demonstrating with the StreamingAPI example?
If we want to demonstrate response streaming, then we shouldn't invoke it through API Gateway at all, as it doesn't support streaming:
https://aws.amazon.com/blogs/compute/introducing-aws-lambda-response-streaming/

We could expose this as Lambda URL, though, if this is the goal.

**Comment by scottgerring** [comment]
> @scottgerring I'm wondering what are we demonstrating with the StreamingAPI example? If we want to demonstrate response streaming, then we shouldn't invoke it through API Gateway at all, as it doesn't support streaming: https://aws.amazon.com/blogs/compute/introducing-aws-lambda-response-streaming/
> 
> We could expose this as Lambda URL, though, if this is the goal.

the stream handlers are streaming in the java sense, not the HTTP sense - they're just there so you can read and write back from the request and response directly without any intermediate serialization happening for you. There's some doco on it [here](https://docs.aws.amazon.com/lambda/latest/dg/java-handler.html).

From our perspective it's valuable to show that you can use PT with this sort of request handler too. In the example we have:

https://github.com/aws-powertools/powertools-lambda-java/blob/8e4173a086158a539d3ab040f0a0d274807c00eb/examples/powertools-examples-core/sam/src/main/java/helloworld/AppStream.java#L33-L38

If you read between the lines a bit, you could imagine that the user needs to do custom serialization on the response, so they have to use a stream handler. On the request side, they just want to deserialize things normally, so they use ObjectMapper for that. But we don't write any response! Maybe we could return something that makes it make more sense? 🤷
