### ISSUE TITLE
Feat: Add support for POWERTOOLS_LOGGER_LOG_EVENT to the logging module

### ISSUE THREAD

**Issue by AlexeySoshin** [aws-powertools/powertools-lambda-java#1444]
### Summary

`POWERTOOLS_LOGGER_LOG_EVENT` is a flag that exists in the examples, but is not supported by the library. The other libraries support it (e.g., [python](https://docs.powertools.aws.dev/lambda/python/latest/#environment-variables)) so we should too. When we get a Lambda event, if this environment variable is set, we log the event itself. This can be done programatically at the moment. 

### Why is this needed?

This could confuse engineers that would expect the `POWERTOOLS_LOGGER_LOG_EVENT` to control the behaviour of the logger somehow.

### Which area does this relate to?

Other

### Solution

The `POWERTOOLS_LOGGER_LOG_EVENT` should be implemented.

### Acknowledgment

- [X] This request meets [Powertools for AWS Lambda (Java) Tenets](https://docs.powertools.aws.dev/lambda-java/#tenets)
- [ ] Should this be considered in other Powertools for AWS Lambda (Java) languages? i.e. [Python](https://github.com/aws-powertools/powertools-lambda-python/), [TypeScript](https://github.com/aws-powertools/powertools-lambda-typescript/)

**Comment by scottgerring** [comment]
Nice catch! Really doesn't seem to be referenced anywhere apart from example deployment code.

**Comment by jeromevdl** [comment]
fixed, will be released after tomorrow
