### ISSUE TITLE
Examples: Add a terraform example for core modules

### ISSUE THREAD

**Issue by jeromevdl** [aws-powertools/powertools-lambda-java#1445]
### What were you searching in the docs?

An example for deploying a lambda function with powertools using Terraform

### How can we improve?

Create an example

### Acknowledgment

- [X] I understand the final update might be different from my proposed suggestion, or refused.

**Comment by skal111** [comment]
Would love to help here

**Comment by jeromevdl** [comment]
closed with #1478
