### ISSUE TITLE
Docs: fix line highlight for dark mode

### ISSUE THREAD

**Issue by am29d** [aws-powertools/powertools-lambda-java#1452]
### What were you searching in the docs?

The line highlight in dark mode is unreadable

<img width="675" alt="Screenshot 2023-10-02 at 09 48 16" src="https://github.com/aws-powertools/powertools-lambda-java/assets/2674178/2107bcbf-f6b5-400e-bf19-d6ae6e416efe">

### How can we improve?

Upgrade mkdocs to 9.3.2 and change the custom CSS

### Acknowledgment

- [X] I understand the final update might be different from my proposed suggestion, or refused.

**Comment by jeromevdl** [comment]
fixed with #1453
