### ISSUE TITLE
Build fails - json-schema.org returns 403 on github runners

### ISSUE THREAD

**Issue by scottgerring** [aws-powertools/powertools-lambda-java#1455]
Our builds have started failing in the powertools-validation unit tests.  The `ValidationAspectTest` tries to do some validation that requires the retrieval of a schema from [https://json-schema.org/draft/2019-09/meta/core](https://json-schema.org/draft/2019-09/meta/core) - this works locally, but seems to be blocked on Github Actions, returning a 403. 

**What were you trying to accomplish?**

## Expected Behavior
Unit tests work everywhere.

## Possible Solution
Let's talk to the json-schema team if possible to try work out why this is 403ing from github, and if there is a risk of this happening from within Lambdas as well. 

Another option could be using the `uriMappings` [mentioned in the documentation](https://github.com/networknt/json-schema-validator/blob/master/doc/config.md) for the unit test itself, to provide local copies of the schema tested to avoid the call out from the actions runner to the internet.

## Steps to Reproduce (for bugs)
Run any build from the github runners.

**Comment by jeromevdl** [comment]
https://json-schema.org/draft/2019-09/meta/core is actually this file: https://github.com/aws-powertools/powertools-lambda-java/blob/main/powertools-validation/src/main/resources/schemas/meta/core

**Comment by jeromevdl** [comment]
Opened an issue here: https://github.com/networknt/json-schema-validator/issues/867
