### ISSUE TITLE
Maintenance: Lint/validate examples Iac

### ISSUE THREAD

**Issue by jeromevdl** [aws-powertools/powertools-lambda-java#1459]
### Summary

We should validate the example IaC:
- validate the template (lint), ex: `sam validate --lint`
- validate that it "works", ex: `sam build` (we already have the compilation with maven/gradle)

Not only for SAM but for others too.

### Why is this needed?

Make sure the provided templates (IaC) are working.

### Which area does this relate to?

Governance, Tests

### Solution

Use `sam validate --lint` (see https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/validate-cfn-lint.html and https://github.com/aws-cloudformation/cfn-lint#config-file) + `sam build` for SAM.

See also https://awslabs.github.io/serverless-rules/cfn-lint/

For terraform, use `terraform validate` and `tflint`.

### Acknowledgment

- [X] This request meets [Powertools for AWS Lambda (Java) Tenets](https://docs.powertools.aws.dev/lambda-java/#tenets)
- [ ] Should this be considered in other Powertools for AWS Lambda (Java) languages? i.e. [Python](https://github.com/aws-powertools/powertools-lambda-python/), [TypeScript](https://github.com/aws-powertools/powertools-lambda-typescript/)

**Comment by jasoniharris** [comment]
Please assign this to me.

**Comment by jeromevdl** [comment]
note that it is done for terraform already: https://github.com/aws-powertools/powertools-lambda-java/blob/main/.github/workflows/pr_build.yml#L82-L109

**Comment by jeromevdl** [comment]
Also, if you could extract this plus what you will do for SAM in a `pr_iac_lint.yml`, so that we don't have all these `if java 11` everywhere.
