### ISSUE TITLE
Maintenance: Fix DynamoDBLocal 2.0.0 update for v2

### ISSUE THREAD

**Issue by scottgerring** [aws-powertools/powertools-lambda-java#1464]
### Summary

DynamoDBLocal, used in `powertools-examples-idempotency`, should be upgraded from 1.22.0 to 2.0.0. Dependabot tried to do this as part of #1255, but this appears to break in java 8. 

As we are removing Java 8 examples in v2 in #1466, we should take this update, roll it into the branch, and make sure that everything works. 

### Why is this needed?

Basic maintenance - tracking dependencies. 

### Which area does this relate to?

Other

### Acknowledgment

- [X] This request meets [Powertools for AWS Lambda (Java) Tenets](https://docs.powertools.aws.dev/lambda-java/#tenets)
- [ ] Should this be considered in other Powertools for AWS Lambda (Java) languages? i.e. [Python](https://github.com/aws-powertools/powertools-lambda-python/), [TypeScript](https://github.com/aws-powertools/powertools-lambda-typescript/)

**Comment by jdoherty** [comment]
I can take a look at this :-)

**Comment by scottgerring** [comment]
Sweet thanks @jdoherty !

**Comment by jeromevdl** [comment]
DynamoDBLocal v2 is not compatible with java 8 anymore, we cannot upgrade

**Comment by scottgerring** [comment]
@jeromevdl maybe time for that conversation again eh.
