### ISSUE TITLE
Exceptions not showing in Traces

### ISSUE THREAD

**Issue by dhcrees** [aws-powertools/powertools-lambda-java#1521]
Trying to add PowerTools to an existing Java project.   We've used X-Ray previously direct through the SDK without any problems.  Initially I thought everything was find adding the @Tracing annotation (Much simpler than the SDK).  But as a test I added some code into my handler to deliberately throw a null pointer exception.

I can see through cloud watch that catch block is being run and I receive a 500 error back through APIG but in the Traces section everything is showing as green and no error is captured.  Am I missing something with my setup?

Using the SDK adding code like AWSXRay.getCurrentSubsegment().addException(exception); will display errors in the Trace results, but this does not seem to work using PowerTools ?

**Comment by jeromevdl** [comment]
Hi @dhcrees, did you find the problem?
