### ISSUE TITLE
Log level not restored at the end of execution

### ISSUE THREAD

**Issue by jeromevdl** [aws-powertools/powertools-lambda-java#1528]
The log level is not restored to its initial version properly in logging module.

https://github.com/aws-powertools/powertools-lambda-java/blob/628a2ca93223df2b2962d1bc122f32a6f572b382/powertools-logging/src/main/java/software/amazon/lambda/powertools/logging/internal/LambdaLoggingAspect.java#L90 should be done before initializing the log level (l76)

**Comment by scottgerring** [comment]
I fixed this in the attached branch, but i'm not sure it's right. 

When we invoke a function with a sampling rate, we decide per invocation whether or not to bump the level down to DEBUG, including more info for the current execution:
https://github.com/aws-powertools/powertools-lambda-java/blob/628a2ca93223df2b2962d1bc122f32a6f572b382/powertools-logging/src/main/java/software/amazon/lambda/powertools/logging/internal/LambdaLoggingAspect.java#L111-L116

If we decide _not to_, we switch back to the "normal level":

https://github.com/aws-powertools/powertools-lambda-java/blob/628a2ca93223df2b2962d1bc122f32a6f572b382/powertools-logging/src/main/java/software/amazon/lambda/powertools/logging/internal/LambdaLoggingAspect.java#L168-L176

So what's the normal level? At the moment in `main` it is the level that is set after the precedence of the different configuration options are taken into account. 

https://github.com/aws-powertools/powertools-lambda-java/blob/628a2ca93223df2b2962d1bc122f32a6f572b382/powertools-logging/src/main/java/software/amazon/lambda/powertools/logging/internal/LambdaLoggingAspect.java#L76-L90

This feels like the right value to switch back to to me. If we change this to reflect the level _before_ we consider the environment variables as in my linked PR, we'll see things like this:

1. First execution - WARN - taken from POWERTOOLS_LOG_LEVLE
2. Second execution - sampled - DEBUG
3. Third execution - ERROR - reset back to the configuration before the environment variables are configured - taken from log4j2.xml

@jeromevdl it's late and I feel like i've have missed something obvious :D For that, there is the PR ready to go ;)

**Comment by jeromevdl** [comment]
yes, the third step is not good, it should be reset to powertools log level, not log4j2.xml, we can close this issue as it's actually better like this.
