### ISSUE TITLE
Maintenance: update jackson and aws-xray-recorder dependencies together

### ISSUE THREAD

**Issue by roamingthings** [aws-powertools/powertools-lambda-java#1538]
### Summary

Jackson 2.16.0 introduces some breaking changes that require to update the AWS X-Ray Recorder dependencies to 2.15.0.

### Why is this needed?

We need to be careful to update both dependencies at once to prevent breaking applications. There are other breaking changes in Jackson 2.16.0 (e.g. new behavior of [`DefaultPrettyPrinter`](https://github.com/FasterXML/jackson-core/pull/1042)) that may also affect this project. The `DefaultPrettyPrinter` is used in [`JacksonFactoryCopy.java`](https://github.com/aws-powertools/powertools-lambda-java/blob/bb9bb2e540b58938caf29a46731f4fedc8fea155/powertools-logging/src/main/java/software/amazon/lambda/powertools/logging/internal/JacksonFactoryCopy.java#L128)

### Solution

Update both dependencies and check for any unwanted behavior

### Acknowledgment

- [X] This request meets [Powertools for AWS Lambda (Java) Tenets](https://docs.powertools.aws.dev/lambda-java/#tenets)
- [ ] Should this be considered in other Powertools for AWS Lambda (Java) languages? i.e. [Python](https://github.com/aws-powertools/powertools-lambda-python/), [TypeScript](https://github.com/aws-powertools/powertools-lambda-typescript/)

**Comment by roamingthings** [comment]
For reference: [Full Jackson 2.16.0 release notes](https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.16)

**Comment by jeromevdl** [comment]
Thanks for reporting this @roamingthings, we'll include this in v2. 
Please note that we now restrict our development on v1 to the strict minimum (bug fixes and security patches) => See https://github.com/aws-powertools/powertools-lambda-java/issues/1522

**Comment by subhash686** [comment]
I would like to help with this.

**Comment by subhash686** [comment]
I created a PR against v2 branch. Did not see any breaking changes like compile errors or failed tests after updating the versions. Please review when you get a chance and advise if I need to run any extra steps in such cases.
