### ISSUE TITLE
v2: Example logging configuration needs to be updated

### ISSUE THREAD

**Issue by scottgerring** [aws-powertools/powertools-lambda-java#1543]
In the v2 branch, in the log4j2.xml files in each of the examples, we still reference `LambdaJsonLayout`:

https://github.com/aws-powertools/powertools-lambda-java/blob/fb14bcfee1aae8e03b8c8081b2478edefc9b5b87/examples/powertools-examples-parameters/src/main/resources/log4j2.xml#L3-L7

We need to update this to reflect the logging changes:

https://github.com/aws-powertools/powertools-lambda-java/blob/fb14bcfee1aae8e03b8c8081b2478edefc9b5b87/docs/core/logging.md?plain=1#L211-L215

**Comment by jeromevdl** [comment]
Weird, this is super old... same problem in serialization example and tracing tests

**Comment by ritigupt1** [comment]
@scottgerring we can close this as the changes are already merged #1545

**Comment by scottgerring** [comment]
Yes!
