### ISSUE TITLE
Use jackson-jr where possible

### ISSUE THREAD

**Issue by driverpt** [aws-powertools/powertools-lambda-java#761]
**Is your feature request related to a problem? Please describe.**
Coldstarts in Lambda

**Describe the solution you'd like**
Use of `jackson-jr` for faster startup time

**Describe alternatives you've considered**
N/A

**Additional context**
It's recommended by AWS the usage of `jackson-jr` where possible in the [Documentation](https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/lambda-optimize-starttime.html)

**Comment by pankajagrawal16** [comment]
Thanks for opening this issue @driverpt.  It will definitely be great to use jackson-jr instead. As of now, there will be other libraries which which end up importing jackson anyways, but if powertools itself can stop using it, is something definitely worth evaluating.

**Comment by driverpt** [comment]
Can't we just include a shaded copy of Jackson JR instead of having External Dependency? Similar to what was already done in AWS SDK for Java V2 ?

**Comment by Neuw84** [comment]
Hi, 
I would like to contribute to the project. Quite good experience with Java and Lambda specifically from my previous role. 
Could I work on this?

**Comment by jeromevdl** [comment]
@Neuw84 Did you have a look at this? I'm interested to know what could be done here. As we already have moving stuff on metrics (#944) and logging (#965), that will cause breaking changes and imply a v2, maybe it's an opportunity to also look at the serialization fwk... But as mentioned by @pankajagrawal16, other libraries are importing jackson, so we would end up with more libraries in the end...

**Comment by msailes** [comment]
Which other libraries are we thinking off? 

The managed runtimes uses Jackson, but they change the package name of it, so I don't think we should consider that.

**Comment by jeromevdl** [comment]
I thought the log4j json layout library was using jackson, but no. It's worth having a deeper analysis, but maybe I'm wrong... (would be great).

**Comment by jeromevdl** [comment]
After analysis, several libraries are using jackson-databind:
- aws-java-sdk-core and jmespath-java, both used in x-ray (tracing module)
- aws-embedded-metrics (metrics module)

We could get rid of it and use something else in powertools but it would lead to an additional library then, and bigger jars, bigger cold starts...
